### ISSUE TITLE
untested examples?

### ISSUE THREAD

**Issue by dneise** [cta-observatory/ctapipe#931] opened 2019-01-24 07:29 UTC
I believe none of the examples in `ctapipe/example` is currently tested in a pytest. 

I think untested examples can easily outdate and then confuse more than they help.

**Comment by kosack** [comment] 2019-01-28 13:13
agreed - eventually however I think they may all move to notebooks that get automatically inserted into the documentation (as we discussed), but that may take some time.  

So for now, we could just execute them like we do the notebooks... They are sort of integration tests, so we could make a tests/ directory with a test-runner that marks them as `pytest.mark.integration` (so they can be easily deactivated for quick testing), and just have a single test that loops through them and runs each...)

**Comment by kosack** [comment] 2019-01-28 13:16
We can also then identify which ones are outdated and should be removed.  A few might be useful to turn into real Tools (and move to `ctapipe/tools`), like `muon_reconstruction` and `display_summed_images`, which are already somewhat useful.

**Comment by dneise** [comment] 2019-01-29 10:45
Karl works on this in #941

**Comment by Tobychev** [comment] 2023-02-23 15:09
@kosack I think this can be closed by now?

**Comment by kosack** [comment] 2023-02-23 15:12
Let me check - I think we can probably remove the examples directory, but I would like to move a few into notebooks.  The only example I use that i find very useful for debugging is `load_one_event.py`

**Comment by maxnoe** [comment] 2023-02-23 15:19
The `examples/` folder is still tehre and contains a lot of somewhat useful but unstructured example code.

This should be either moved to docstrings, example notebooks or removed.

In the current state of this repo, the issue is still valid.

**Comment by kosack** [comment] 2023-02-23 15:54
yes, following what I said above - I will make a PR that moves anything useful to notebooks.

**Comment by maxnoe** [comment] 2023-02-23 16:47
Could also be docstrings of classes (e.g. the `load_one_event` could either be in the docstring of `ArrayEventContainer` or of `(SimTel)EventSource`

**Comment by maxnoe** [comment] 2023-03-01 10:25
This is basically a duplicate of #657, closing this one

**Closed by maxnoe** 2023-03-01 10:25 UTC
