### ISSUE TITLE
calibration info needed to support reco and muon processing

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#462] opened 2017-07-04 14:00 UTC
right now there are a number of hard-coded values in code like `reco.ImPACTReconstructor` and `image.muon` for things like pedestal values and single-PE widths.  We should come up with a common way to store and access these in the `ctapipe.instrument` module.   This is not so different from other instrumental parameters like the atmosphere profile. 

At the very least, the values should be stored in a file that is accessable through `ctapipe.utils.datasets.get_dataset` (which searches for files in `ctapipe_resources` (defaults) or any directory listed in `$CTAPIPE_SVC_PATH` (user-specified).

It could make sense that all analyses should assume that a set of required files are in a directory accessible by `get_dataset`, so we can build analysis configurations that way.

My suggestion for a quick way to do this would be to 

1.  define a common file-name and format for each piece of required info (this could be a FITS file, text file of some kind, or even a DB file like sqlite)
2. put examples/defaults in `ctapipe_resources`
3. provide a `Tool` that extracts the info from MC files and creates the needed files, if possible (perhaps modifying `ctapipe-dump-instrument`), to make it easy to build an analysis config directory with all needed inputs

eventually, we want the interface to work regardless of whether the data are in files or databases, but that could be a 2-step process where the user first runs a Tool to extract the necessary info from a DB and write it to a set of files, sets `$CTAPIPE_SVC_PATH`, and then runs the analysis (this would be ideal for batch processing where we don't want to access a DB if possible, since there could be many connections)

Any other ideas?

**Comment by maxnoe** [comment] 2020-10-26 11:23
This is basically solved by using `TelescopeParameters` for simple things and is a duplicate of monitoring data handling for more complex  things.

Also, most of this is now available in the mon data containers at least for simtel files.

**Closed by maxnoe** 2020-10-26 11:23 UTC
