### ISSUE TITLE
Make integration correction configurable

### ISSUE THREAD

**Issue by MaxNoe** [cta-observatory/ctapipe#1418] opened 2020-09-14 17:00 UTC
A couple of (late) comments on this:

> * Adding a `_calculate_correction` method to the ImageExtractors, so one can define the appropriate way to calculate the correction for each particular extractor. For a noise-less unit pulse the resulting charge from an ImageExtractor should always equal 1, ensuring the correct units for the resulting charge - this is the goal of the correction factor.

It does not seem to me that the goal is the right one. Real or simulated pulses are composed of photons with a time structure. Take a single p.e. pulse shape (like LST's low-gain one) which has some "ringing" with undershoots after the main peak. For the single p.e. shape, if you integrate a number of samples which don't include any undershoot, the correction factor would be <1. But for a real pulse (be it a calibration pulse, or a pulse from a shower), with a time structure, the main peaks of the photon pulses will fill the undershoots of earlier photons, so the mean or typical pulse will have a pretty different shape, and the correction will be wrong.

> * Removing the ability to skip over the correction if there is no reference pulse defined.

I actually think it would be nice, at least for testing purposes, if the pulse correction could be skipped altogether in some easy way, through a line in the configuration file.

_Originally posted by @moralejo in https://github.com/cta-observatory/ctapipe/pull/1242#issuecomment-692174072_

**Comment by watsonjj** [comment] 2020-09-18 07:34
This is mostly a duplicate of #1376. As I suggested in this issue, a bool trait could be added to the extractors to disable the correction

**Closed** 2020-09-22 13:01 UTC
