### ISSUE TITLE
read_table does not load units for instrument description

### ISSUE THREAD

**Issue by LukasNickel** [cta-observatory/ctapipe#1669] opened 2021-03-29 11:23 UTC
The instrument description does not have the units stored as `_UNIT` in the table metadata. For this reason `read_data()` will not assign a unit to e.g. the focal length, whereas `astropy.table.Table.read()` does (`read_table` uses pytables internally and converts to an astropy table later).

We dont use it internally, but it is a bit surprising to see.

![image](https://user-images.githubusercontent.com/15281090/112829577-99355900-9091-11eb-8abc-6fba4cc41e65.png)

**Comment by maxnoe** [comment] 2021-03-29 11:37
This is because these are stored using `astropy`. We could add our own metadata to make them readable with both.

However, reading the subarray should be done using `SubarrayDescription.from_hdf` anyways, which handles this correctly.

I agree that for consistency, we should use the same method, but this is then a duplicate of https://github.com/cta-observatory/ctapipe/issues/1449

**Closed** 2021-03-29 11:38 UTC
Labels: duplicate
