### ISSUE TITLE
traits of Components are not always possible to change after construction

### ISSUE THREAD

**Issue by kosack** [cta-observatory/ctapipe#1997] opened 2022-07-06 16:05 UTC
**Describe the bug**
Some `Traits` of `Components` can be changed after construction and everything still works fine.  However, some cannot.
For example, if the user changes the focal length choice of an `EventSource` after construction, the changes are not propagated into the SubarrayDescription. 

```py3
with EventSource(filename) as source:
    source.focal_length_choice='nominal'
    source.subarray.tel[1].camera.geometry.frame # still uses effective 
```

This may be unexpected behavior for a user.

**Expected behavior**
Either it should work as expected (changes update the object using Trait callbacks), or we should at least document which traits should not be changed after.

**Comment by maxnoe** [comment] 2023-01-04 16:07
This was discussed elsewhere, I think it is a good tradeoff between complexity and ease-of-use to assume that a `Component` is basically immutable after construction.

This is not a bug, maybe a design decision question.

Adding `onchange` handlers to all traitlets is certainly not what we want to do.

I'll close this as won't fix for now, maybe we should document this at some high-level design decision point...

**Closed by maxnoe** 2023-01-04 16:07 UTC
Labels: bug
